// GENERATED by scripts/build-brand.mjs — do not edit by hand.
// Source geometry: scripts/{outline,wordmark,brand}.mjs

/** The VAYRO symbol: a chevron whose ascending arm turns.
 *  100x100 viewBox. Use at >= 24px. */
export const SYMBOL_PATH = "M14.513 15.815L51.093 93.854L55.613 94L81.403 47.109L83.504 39.84L85.487 6.783L72.435 6L70.628 36.118L68.527 43.388L56.543 65.177L52.023 65.031L26.352 10.265Z";

/** Optically corrected variant for <= 20px (favicon, zipper, embroidery). */
export const SYMBOL_MICRO_PATH = "M11.744 14.493L50.345 96.843L55.203 97L84.249 44.188L86.282 37.156L88.256 4.252L67.392 3L65.699 31.207L63.667 38.239L56.69 50.925L51.832 50.768L30.67 5.622Z";

/** Custom wordmark glyphs. Cap height 100, stem 14.2, tracking 17. */
export const GLYPH_PATHS: Record<string, { w: number; d: string }> = {
  "V": {
    "w": 76,
    "d": "M6.64 -2.52L36.08 74.96L39.92 74.96L69.36 -2.52L82.64 2.52L39.92 114.94L36.08 114.94L-6.64 2.52Z"
  },
  "A": {
    "w": 78,
    "d": "M-6.61 97.42L37.04 -14.51L40.96 -14.51L84.61 97.42L71.39 102.58L40.96 24.57L37.04 24.57L6.61 102.58ZM13.5 63.5L64.5 63.5L64.5 76.9L13.5 76.9Z"
  },
  "Y": {
    "w": 74,
    "d": "M5.89 -3.96L44.1 52.83L44.1 100L29.9 100L29.9 57.17L-5.89 3.96ZM31.11 51.04L68.11 -3.96L79.89 3.96L42.89 58.96Z"
  },
  "R": {
    "w": 70,
    "d": "M0 0L14.2 0L14.2 100L0 100ZM14.2 0H41.5C56.4 0 67.4 10.4 67.4 25.1S56.4 50.2 41.5 50.2H14.2ZM14.2 36.4H41.5C48.2 36.4 53.2 31.6 53.2 25.1S48.2 13.8 41.5 13.8H14.2ZM28.5 44L45.6 44L70 100L55.4 100Z"
  },
  "O": {
    "w": 80,
    "d": "M40 0C64.6 0 80 19.25 80 50C80 80.75 64.6 100 48.5 100H31.5C15.4 100 0 80.75 0 50C0 19.25 15.4 0 40 0ZM40 14.2C24.13 14.2 14.2 27.98 14.2 50C14.2 72.02 24.13 85.8 34.6 85.8H45.4C55.87 85.8 65.8 72.02 65.8 50C65.8 27.98 55.87 14.2 40 14.2Z"
  }
};

export const WORDMARK_WIDTH = 446;
export const CAP_HEIGHT = 100;
export const TRACKING = 17;
export const STEM_WEIGHT = 14.2;

/** Symbol height as a multiple of wordmark cap height, optically matched. */
export const LOCKUP_SYMBOL_RATIO = 1.3;
export const LOCKUP_GAP_RATIO = 0.46;

/** Minimum clear space around any lockup = this multiple of symbol height. */
export const CLEAR_SPACE_RATIO = 0.28;

/** Contour pattern tile. */
/** Combination mark: the symbol substituted for the V of VAYRO. */
export const LOGOTYPE = {"inner":"<g transform=\"translate(-16.49 -6.82) scale(1.14)\"><path d=\"M14.513 15.815L51.093 93.854L55.613 94L81.403 47.109L83.504 39.84L85.487 6.783L72.435 6L70.628 36.118L68.527 43.388L56.543 65.177L52.023 65.031L26.352 10.265Z\"/></g><g transform=\"translate(92.65 0)\"><path d=\"M-6.61 97.42L37.04 -14.51L40.96 -14.51L84.61 97.42L71.39 102.58L40.96 24.57L37.04 24.57L6.61 102.58ZM13.5 63.5L64.5 63.5L64.5 76.9L13.5 76.9Z\"/></g><g transform=\"translate(183.65 0)\"><path d=\"M5.89 -3.96L44.1 52.83L44.1 100L29.9 100L29.9 57.17L-5.89 3.96ZM31.11 51.04L68.11 -3.96L79.89 3.96L42.89 58.96Z\"/></g><g transform=\"translate(270.65 0)\"><path d=\"M0 0L14.2 0L14.2 100L0 100ZM14.2 0H41.5C56.4 0 67.4 10.4 67.4 25.1S56.4 50.2 41.5 50.2H14.2ZM14.2 36.4H41.5C48.2 36.4 53.2 31.6 53.2 25.1S48.2 13.8 41.5 13.8H14.2ZM28.5 44L45.6 44L70 100L55.4 100Z\"/></g><g transform=\"translate(353.65 0)\"><path d=\"M40 0C64.6 0 80 19.25 80 50C80 80.75 64.6 100 48.5 100H31.5C15.4 100 0 80.75 0 50C0 19.25 15.4 0 40 0ZM40 14.2C24.13 14.2 14.2 27.98 14.2 50C14.2 72.02 24.13 85.8 34.6 85.8H45.4C55.87 85.8 65.8 72.02 65.8 50C65.8 27.98 55.87 14.2 40 14.2Z\"/></g>","width":433.65,"height":100};

export const LOGOTYPE_STACKED = {"inner":"<g transform=\"translate(-24.74 -10.23) scale(1.7)\"><path d=\"M14.513 15.815L51.093 93.854L55.613 94L81.403 47.109L83.504 39.84L85.487 6.783L72.435 6L70.628 36.118L68.527 43.388L56.543 65.177L52.023 65.031L26.352 10.265Z\"/></g><g transform=\"translate(0 172) scale(0.31)\"><g transform=\"translate(0 0)\"><path d=\"M6.64 -2.52L36.08 74.96L39.92 74.96L69.36 -2.52L82.64 2.52L39.92 114.94L36.08 114.94L-6.64 2.52Z\"/></g><g transform=\"translate(78 0)\"><path d=\"M-6.61 97.42L37.04 -14.51L40.96 -14.51L84.61 97.42L71.39 102.58L40.96 24.57L37.04 24.57L6.61 102.58ZM13.5 63.5L64.5 63.5L64.5 76.9L13.5 76.9Z\"/></g><g transform=\"translate(158 0)\"><path d=\"M5.89 -3.96L44.1 52.83L44.1 100L29.9 100L29.9 57.17L-5.89 3.96ZM31.11 51.04L68.11 -3.96L79.89 3.96L42.89 58.96Z\"/></g><g transform=\"translate(234 0)\"><path d=\"M0 0L14.2 0L14.2 100L0 100ZM14.2 0H41.5C56.4 0 67.4 10.4 67.4 25.1S56.4 50.2 41.5 50.2H14.2ZM14.2 36.4H41.5C48.2 36.4 53.2 31.6 53.2 25.1S48.2 13.8 41.5 13.8H14.2ZM28.5 44L45.6 44L70 100L55.4 100Z\"/></g><g transform=\"translate(306 0)\"><path d=\"M40 0C64.6 0 80 19.25 80 50C80 80.75 64.6 100 48.5 100H31.5C15.4 100 0 80.75 0 50C0 19.25 15.4 0 40 0ZM40 14.2C24.13 14.2 14.2 27.98 14.2 50C14.2 72.02 24.13 85.8 34.6 85.8H45.4C55.87 85.8 65.8 72.02 65.8 50C65.8 27.98 55.87 14.2 40 14.2Z\"/></g></g>","width":120.98,"height":203.34};

/** Spacing the logotype is drawn at. Documented in the guidelines. */
export const LOGOTYPE_GAP = 12;
export const LOGOTYPE_TRACK = 13;

export const PATTERN_TILE = 120;
export const PATTERN_PATH = "M0 -15L60 0L120 -15M0 15L60 30L120 15M0 45L60 60L120 45M0 75L60 90L120 75M0 105L60 120L120 105M0 135L60 150L120 135";
