import { writeFileSync, mkdirSync } from 'node:fs';
import * as B from './brand.mjs';

const OUT = new URL('../public/brand/', import.meta.url);
mkdirSync(OUT, { recursive: true });
const w = (name, content) => { writeFileSync(new URL(name, OUT), content); return name; };

const { ink, ivory } = B.COLOR;
const files = [];
const sym = (fill) => B.svg(100, 100, `<path d="${B.SYMBOL.d}"/>`, { fill });
const symMicro = (fill) => B.svg(100, 100, `<path d="${B.SYMBOL_MICRO.d}"/>`, { fill });
const wm = (fill) => B.svg(B.WORDMARK.width, B.CAP, B.WORDMARK.svg, { fill });
const lh = B.lockupHorizontal(), ls = B.lockupStacked();

files.push(w('vayro-symbol.svg',            sym(ink)));
files.push(w('vayro-symbol-ivory.svg',      sym(ivory)));
files.push(w('vayro-symbol-micro.svg',      symMicro(ink)));
files.push(w('vayro-symbol-micro-ivory.svg',symMicro(ivory)));
files.push(w('vayro-wordmark.svg',          wm(ink)));
files.push(w('vayro-wordmark-ivory.svg',    wm(ivory)));
files.push(w('vayro-lockup-horizontal.svg',       B.svg(lh.width, lh.height, lh.inner, { fill: ink })));
files.push(w('vayro-lockup-horizontal-ivory.svg', B.svg(lh.width, lh.height, lh.inner, { fill: ivory })));
files.push(w('vayro-lockup-stacked.svg',          B.svg(ls.width, ls.height, ls.inner, { fill: ink })));
files.push(w('vayro-lockup-stacked-ivory.svg',    B.svg(ls.width, ls.height, ls.inner, { fill: ivory })));

/* app icon / monogram tile — ink field, ivory mark, 22% optical padding */
const tile = (bg, fg, radius = 0) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">`
  + `<rect width="512" height="512" rx="${radius}" fill="${bg}"/>`
  + `<g transform="translate(112 112) scale(2.88)"><path d="${B.SYMBOL.d}" fill="${fg}"/></g></svg>`;
files.push(w('vayro-app-icon.svg',       tile(ink, ivory, 0)));
files.push(w('vayro-app-icon-round.svg', tile(ink, ivory, 114)));
files.push(w('vayro-monogram-ivory.svg', tile(ivory, ink, 0)));

/* favicon — uses the micro optical size */
files.push(w('favicon.svg',
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">`
  + `<rect width="100" height="100" fill="${ink}"/>`
  + `<g transform="translate(14 14) scale(0.72)"><path d="${B.SYMBOL_MICRO.d}" fill="${ivory}"/></g></svg>`));

/* tileable pattern — contour chevrons */
const p = B.pattern({ size: 120 });
files.push(w('vayro-pattern.svg',
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${p.size} ${p.size}" width="${p.size}" height="${p.size}">`
  + `<path d="${p.d}" fill="none" stroke="${ink}" stroke-width="${p.stroke}" stroke-linejoin="round" opacity="0.18"/></svg>`));

/* ---- TypeScript art constants consumed by React components ---- */
mkdirSync(new URL('../src/lib/', import.meta.url), { recursive: true });
writeFileSync(new URL('../src/lib/brand-art.ts', import.meta.url),
`// GENERATED by scripts/build-brand.mjs — do not edit by hand.
// Source geometry: scripts/{outline,wordmark,brand}.mjs

/** The VAYRO symbol: a chevron whose ascending arm turns.
 *  100x100 viewBox. Use at >= 24px. */
export const SYMBOL_PATH = ${JSON.stringify(B.SYMBOL.d)};

/** Optically corrected variant for <= 20px (favicon, zipper, embroidery). */
export const SYMBOL_MICRO_PATH = ${JSON.stringify(B.SYMBOL_MICRO.d)};

/** Custom wordmark glyphs. Cap height ${B.CAP}, stem ${B.STEM}, tracking ${B.TRACK}. */
export const GLYPH_PATHS: Record<string, { w: number; d: string }> = ${JSON.stringify(
  Object.fromEntries(Object.entries(B.GLYPHS).map(([k, g]) => [k, { w: g.w, d: g.d }])), null, 2)};

export const WORDMARK_WIDTH = ${B.WORDMARK.width};
export const CAP_HEIGHT = ${B.CAP};
export const TRACKING = ${B.TRACK};
export const STEM_WEIGHT = ${B.STEM};

/** Symbol height as a multiple of wordmark cap height, optically matched. */
export const LOCKUP_SYMBOL_RATIO = 1.3;
export const LOCKUP_GAP_RATIO = 0.46;

/** Minimum clear space around any lockup = this multiple of symbol height. */
export const CLEAR_SPACE_RATIO = 0.28;

/** Contour pattern tile. */
export const PATTERN_TILE = ${B.pattern({ size: 120 }).size};
export const PATTERN_PATH = ${JSON.stringify(B.pattern({ size: 120 }).d)};
`);

console.log(files.length + 1, 'brand files written');
files.forEach((f) => console.log('  public/brand/' + f));
console.log('  src/lib/brand-art.ts');
